import type { AppId, AppMeta, OSVersion } from "./os-types";

export const VALID_KEY = "VANYA8-BOBEROS";

export const VERSION_LABEL: Record<OSVersion, string> = {
  pro: "BoberOS Pro",
  home: "BoberOS Домашняя",
  max: "BoberOS Max VK EDITION RUSSIA",
};

export const APP_META: Record<AppId, AppMeta> = {
  bpaint: { id: "bpaint", name: "BPaint", color: "from-amber-400 to-orange-500", defaultWidth: 760, defaultHeight: 560, minWidth: 520, minHeight: 420, source: "system", resizable: true },
  boberstore: { id: "boberstore", name: "BoberStore", color: "from-emerald-400 to-teal-600", defaultWidth: 880, defaultHeight: 620, minWidth: 560, minHeight: 420, source: "system", resizable: true },
  mybober: { id: "mybober", name: "Мой бобёр", color: "from-sky-400 to-cyan-600", defaultWidth: 780, defaultHeight: 520, minWidth: 520, minHeight: 380, source: "system", resizable: true },
  notepad: { id: "notepad", name: "Блокнот", color: "from-yellow-300 to-amber-500", defaultWidth: 560, defaultHeight: 460, minWidth: 360, minHeight: 300, source: "system", resizable: true },
  settings: { id: "settings", name: "Настройки", color: "from-slate-400 to-slate-600", defaultWidth: 720, defaultHeight: 580, minWidth: 480, minHeight: 400, source: "system", resizable: true },
  calculator: { id: "calculator", name: "Калькулятор", color: "from-zinc-400 to-zinc-600", defaultWidth: 320, defaultHeight: 480, source: "system", resizable: false },
  boberchat: { id: "boberchat", name: "BoberChat", color: "from-cyan-400 to-blue-500", defaultWidth: 720, defaultHeight: 560, minWidth: 480, minHeight: 400, source: "system", resizable: true },
  boberbrowser: { id: "boberbrowser", name: "BoberBrowser", color: "from-orange-400 to-rose-500", defaultWidth: 880, defaultHeight: 600, minWidth: 560, minHeight: 420, source: "system", resizable: true },
  boberterminal: { id: "boberterminal", name: "Терминал", color: "from-gray-700 to-gray-900", defaultWidth: 640, defaultHeight: 460, minWidth: 420, minHeight: 320, source: "system", resizable: true },
  boberclock: { id: "boberclock", name: "Часы", color: "from-indigo-400 to-violet-600", defaultWidth: 420, defaultHeight: 480, source: "system", resizable: false },
  bobertunes: { id: "bobertunes", name: "BoberTunes", color: "from-pink-400 to-fuchsia-600", defaultWidth: 760, defaultHeight: 560, minWidth: 520, minHeight: 420, source: "system", resizable: true },
  registryeditor: { id: "registryeditor", name: "Редактор Бобра", color: "from-red-500 to-rose-700", defaultWidth: 780, defaultHeight: 560, minWidth: 520, minHeight: 400, source: "system", resizable: true },

  antivirus360: { id: "antivirus360", name: "360", color: "from-green-500 to-emerald-700", defaultWidth: 640, defaultHeight: 500, minWidth: 480, minHeight: 400, source: "store", resizable: true },
  spim: { id: "spim", name: "Спим", color: "from-zinc-500 to-zinc-700", defaultWidth: 900, defaultHeight: 620, minWidth: 560, minHeight: 440, source: "store", resizable: true },
  bobercoin: { id: "bobercoin", name: "BoberCoin", color: "from-yellow-400 to-amber-600", defaultWidth: 560, defaultHeight: 640, minWidth: 420, minHeight: 520, source: "store", resizable: true },
  bobermail: { id: "bobermail", name: "BoberMail", color: "from-red-400 to-rose-600", defaultWidth: 820, defaultHeight: 580, minWidth: 520, minHeight: 400, source: "store", resizable: true },
  boberweather: { id: "boberweather", name: "BoberWeather", color: "from-sky-400 to-cyan-600", defaultWidth: 640, defaultHeight: 560, minWidth: 440, minHeight: 420, source: "store", resizable: true },
  bobermaps: { id: "bobermaps", name: "BoberMaps", color: "from-green-400 to-emerald-600", defaultWidth: 820, defaultHeight: 600, minWidth: 520, minHeight: 420, source: "store", resizable: true },
  bobertube: { id: "bobertube", name: "BoberTube", color: "from-rose-500 to-red-700", defaultWidth: 860, defaultHeight: 600, minWidth: 560, minHeight: 420, source: "store", resizable: true },
  boberoffice: { id: "boberoffice", name: "BoberOffice", color: "from-blue-500 to-indigo-600", defaultWidth: 780, defaultHeight: 600, minWidth: 520, minHeight: 420, source: "store", resizable: true },
  bobercalcpro: { id: "bobercalcpro", name: "BoberCalc Pro", color: "from-purple-500 to-fuchsia-700", defaultWidth: 420, defaultHeight: 580, source: "store", resizable: false },
  bobervpn: { id: "bobervpn", name: "BoberVPN", color: "from-emerald-400 to-green-600", defaultWidth: 560, defaultHeight: 520, minWidth: 420, minHeight: 400, source: "store", resizable: true },
  bobercloud: { id: "bobercloud", name: "BoberCloud", color: "from-cyan-400 to-sky-600", defaultWidth: 780, defaultHeight: 560, minWidth: 520, minHeight: 420, source: "store", resizable: true },
  bobertranslate: { id: "bobertranslate", name: "BoberTranslate", color: "from-violet-400 to-purple-600", defaultWidth: 680, defaultHeight: 540, minWidth: 460, minHeight: 400, source: "store", resizable: true },
  bobermonitor: { id: "bobermonitor", name: "BoberMonitor", color: "from-zinc-600 to-zinc-800", defaultWidth: 720, defaultHeight: 560, minWidth: 520, minHeight: 420, source: "store", resizable: true },
  bobercalendar: { id: "bobercalendar", name: "BoberCalendar", color: "from-rose-400 to-pink-600", defaultWidth: 720, defaultHeight: 580, minWidth: 480, minHeight: 420, source: "store", resizable: true },
  boberstudio: { id: "boberstudio", name: "BoberStudio", color: "from-teal-400 to-cyan-700", defaultWidth: 820, defaultHeight: 600, minWidth: 560, minHeight: 440, source: "store", resizable: true },

  flappybober: { id: "flappybober", name: "Флэппи Бобёр", color: "from-lime-400 to-green-600", defaultWidth: 480, defaultHeight: 640, source: "spim", resizable: false },
  cs2: { id: "cs2", name: "КС2", color: "from-orange-400 to-red-600", defaultWidth: 560, defaultHeight: 440, source: "spim", resizable: false },
  cyberbober: { id: "cyberbober", name: "КиберБобер", color: "from-fuchsia-500 to-purple-700", defaultWidth: 860, defaultHeight: 600, minWidth: 640, minHeight: 480, source: "spim", resizable: true },
  snake: { id: "snake", name: "Змейка Бобра", color: "from-green-400 to-emerald-600", defaultWidth: 520, defaultHeight: 600, minWidth: 420, minHeight: 520, source: "spim", resizable: true },
  game2048: { id: "game2048", name: "2048 Бобра", color: "from-amber-400 to-yellow-600", defaultWidth: 480, defaultHeight: 600, minWidth: 380, minHeight: 520, source: "spim", resizable: true },
  minesweeper: { id: "minesweeper", name: "Сапёр", color: "from-slate-400 to-slate-600", defaultWidth: 480, defaultHeight: 580, minWidth: 400, minHeight: 480, source: "spim", resizable: true },
  memory: { id: "memory", name: "Память", color: "from-rose-400 to-pink-600", defaultWidth: 520, defaultHeight: 600, minWidth: 420, minHeight: 480, source: "spim", resizable: true },
  rps: { id: "rps", name: "Камень-Ножницы-Бумага", color: "from-teal-400 to-cyan-600", defaultWidth: 480, defaultHeight: 560, source: "spim", resizable: false },
  tictactoe: { id: "tictactoe", name: "Крестики-нолики", color: "from-violet-400 to-purple-600", defaultWidth: 440, defaultHeight: 560, source: "spim", resizable: false },
  whackamole: { id: "whackamole", name: "Реакция Бобра", color: "from-orange-400 to-amber-600", defaultWidth: 500, defaultHeight: 600, source: "spim", resizable: false },
  tetris: { id: "tetris", name: "Тетрис Бобра", color: "from-amber-500 to-orange-700", defaultWidth: 520, defaultHeight: 660, minWidth: 420, minHeight: 560, source: "spim", resizable: true },
  pong: { id: "pong", name: "Пинг-Понг Бобра", color: "from-sky-500 to-blue-700", defaultWidth: 720, defaultHeight: 520, minWidth: 520, minHeight: 400, source: "spim", resizable: true },
  breakout: { id: "breakout", name: "Арканоид Бобра", color: "from-indigo-500 to-violet-700", defaultWidth: 600, defaultHeight: 620, minWidth: 460, minHeight: 520, source: "spim", resizable: true },
  sokoban: { id: "sokoban", name: "Сокобан Бобра", color: "from-stone-500 to-amber-700", defaultWidth: 640, defaultHeight: 600, minWidth: 460, minHeight: 460, source: "spim", resizable: true },
  fifteen: { id: "fifteen", name: "Пятнашки", color: "from-yellow-400 to-amber-600", defaultWidth: 440, defaultHeight: 540, source: "spim", resizable: false },
  hangman: { id: "hangman", name: "Виселица", color: "from-rose-500 to-red-700", defaultWidth: 520, defaultHeight: 600, minWidth: 420, minHeight: 480, source: "spim", resizable: true },
  simon: { id: "simon", name: "Симон", color: "from-fuchsia-500 to-pink-700", defaultWidth: 480, defaultHeight: 580, source: "spim", resizable: false },
  dinorunner: { id: "dinorunner", name: "БоброБег", color: "from-emerald-500 to-green-700", defaultWidth: 720, defaultHeight: 520, minWidth: 480, minHeight: 360, source: "spim", resizable: true },
  sudoku: { id: "sudoku", name: "Судоку Бобра", color: "from-amber-500 to-yellow-700", defaultWidth: 520, defaultHeight: 640, minWidth: 440, minHeight: 560, source: "spim", resizable: true },
  connect4: { id: "connect4", name: "Четыре в ряд", color: "from-rose-500 to-red-700", defaultWidth: 560, defaultHeight: 640, minWidth: 460, minHeight: 540, source: "spim", resizable: true },
  wordle: { id: "wordle", name: "БобрВорд", color: "from-green-500 to-emerald-700", defaultWidth: 480, defaultHeight: 680, minWidth: 400, minHeight: 580, source: "spim", resizable: true },
  gallery: { id: "gallery", name: "Галерея", color: "from-pink-400 to-rose-600", defaultWidth: 780, defaultHeight: 560, minWidth: 520, minHeight: 400, source: "system", resizable: true },
  taskmanager: { id: "taskmanager", name: "Диспетчер задач", color: "from-zinc-600 to-zinc-800", defaultWidth: 720, defaultHeight: 560, minWidth: 520, minHeight: 400, source: "system", resizable: true },
  bober3d: { id: "bober3d", name: "Бобр3D", color: "from-zinc-700 to-amber-900", defaultWidth: 800, defaultHeight: 600, minWidth: 560, minHeight: 420, source: "spim", resizable: true },
  parkour: { id: "parkour", name: "БоброПаркур", color: "from-emerald-500 to-green-800", defaultWidth: 800, defaultHeight: 560, minWidth: 520, minHeight: 400, source: "spim", resizable: true },
  rungun: { id: "rungun", name: "Бобр: Штурм", color: "from-red-600 to-amber-800", defaultWidth: 840, defaultHeight: 560, minWidth: 560, minHeight: 420, source: "spim", resizable: true },
};

export const PREINSTALLED: AppId[] = [
  "bpaint",
  "boberstore",
  "mybober",
  "notepad",
  "settings",
  "calculator",
  "boberchat",
  "boberbrowser",
  "boberterminal",
  "boberclock",
  "bobertunes",
  "registryeditor",
  "gallery",
  "taskmanager",
];
